@startuml Cooking_Sequence
skinparam style strictuml
actor Повар
participant "Магазин" as Магазин
participant "Плита" as Плита
participant "Кухня" as Кухня
participant "Стол" as Стол

activate Повар
Повар -> Магазин: ПоходВМагазин()
activate Магазин
Повар -> Магазин: ПокупкаПродуктов()
deactivate Магазин
Повар -> Кухня: ВозвращениеДомой()
activate Кухня
Повар -> Кухня: ПодготовкаИнгредиентов()
Повар -> Плита: ПриготовлениеСоуса()
activate Плита
Повар -> Плита: ПоставитьВоду()
Повар //-- Плита: "send"
Повар -> Плита: ВаркаСпагетти()
Плита --> Повар: "return"
Повар -> Плита: СпагеттиГотовы()
deactivate Плита
Повар -> Кухня: СмешиваниеСпагеттиССоусом()
deactivate Кухня
Повар -> Стол: ПодачаБлюда()
deactivate Повар
@enduml