@startuml Zoo_Classes
class Zoo {
    - name: string
    - enclosures: vector<Enclosure*>
    - zookeepers: vector<Zookeeper*>
    + addEnclosure(enclosure: Enclosure*): void
    + addZookeeper(zookeeper: Zookeeper*): void
    + displayZooInfo(): void
}

class Animal {
    - name: string
    - species: string
    - age: int
    + makeSound(): void
}

class Enclosure {
    - id: int
    - animals: vector<Animal*>
    + addAnimal(animal: Animal*): void
    + displayAnimals(): void
}

class Zookeeper {
    - name: string
    - assignedEnclosure: Enclosure*
    + Zookeeper(name: string)
    + assignEnclosure(enclosure: Enclosure*): void
    + feedAnimals(): void
}

Zoo "1" *-- "1..*" Enclosure
Zoo "1" *-- "1..*" Zookeeper
Enclosure "1" *-- "0..*" Animal
Zookeeper "1" -- "1" Enclosure
@enduml